# Nombre del workflow [opcional]
name: Java CI with Gradle

# Eventos que disparan el workflow [obligatorio]
on:
  # Cada push que se haga a la rama "main" del repositorio remoto
  push:
    branches: [ "main" ]
  # Cada pull request que se haga a la rama "main" del repositorio remoto
  pull_request:
    branches: [ "main" ]

# Trabajos que componen el workflow (uno o varios) [obligatorio] 
jobs:
  # Id del trabajo (agrupa una serie de acciones o etapas a ejecutar)
  # Nota: Cada trabajo de un workflow se ejecuta en un entorno de ejecucuón diferente y, por defecto,
  # cada trabajo se ejecuta en paralelo (En caso de haber dependencia de un trabajo con respecto a otro, puede
  # configurarse para que se ejecuten uno a continuación de otro)
  build:

    # Entorno de ejecución de las acciones o etapas del trabajo
    #runs-on: ubuntu-latest

    # Nota: Si queremos ejecutar las acciones y etapas del trabajo en diferentes entornos de ejecución, podemos hacer lo siguiente:
    # Obtiene el valor de la propiedad o atributo "matrix.os" que contiene el array o lista de entornos de ejecución
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Definimos un array o lista de entornos de ejecución donde queremos ejecutar las acciones o etapas del trabajo
        os: [ubuntu-latest, windows-latest, macOS-latest]

    # Acciones o etapas del trabajo [obligatorio]
    steps:
    # Acción de GitHub (Versión 2 de la Acción "checkout" de GitHub) para clonar el repositorio en el entorno de ejecución indicado más arriba
    - uses: actions/checkout@v2

    # Acción de GitHub (Versión 1 de la Acción "setup-java" de GitHub) que instala y configura la versión 1.8 del JDK de Java en el entorno de ejecución indicado más arriba
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    
    # Comando que da permisos de ejecución al archivo gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Comando para construir la aplicación con Gradle
    - name: Build with Gradle
      run: ./gradlew build

  #publish:

    # Indicamos que este trabajo depende del trabajo con id "build" para que este trabajo se ejecute a continuación del
    # trabajo con id "build" y así evitar que ámbos se ejecuten en paralelo (ejecución por defecto)
    #needs: build